# Generated by Django 4.1.1 on 2022-09-21 14:17

from django.db import migrations, models
import enum


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=enum.auto)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('image1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('image2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('image3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('image4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
            ],
            options={
                'verbose_name_plural': 'Rooms',
            },
        ),
    ]
